site:
  name: 'Виктор Соковнин'
  site: 'https://sokovnin.me'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: Блог
    template: '%s | Виктор Соковнин'
  description: "Статьи про стратегию, рост и монетизацию tech-компаний"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'Виктор Соковнин'
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
    locale: ru_RU

i18n:
  language: ru
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 12

    post:
      isEnabled: true
      permalink: '/blog/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path at /blog
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'blog/category' # Category main path /blog/category/some-category
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'blog/tag' # Tag main path /blog/tag/some-tag
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'light:only' # Оставляем только светлую тему
